pipeline:
  build:
    image: node:latest
    commands:
      - apk add --no-cache make git python gcc g++
      - npm install yarn --global
      - yarn
      - npm run build
matrix:
  NODE_VERSION:
    - latest
    - "7"
    - "6"
