pipeline:
  build:
    image: mhart/alpine-node:7.6.0
    commands:
      - apk add --no-cache make git python gcc g++
      - npm install yarn --global
      - yarn
      - npm run build
matrix:
  NODE_VERSION:
    - latest
    - "7"
    - "6"
